name: Run Unit Tests

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build-node:
    name: Install, Build, Test, & Deploy
    runs-on: ubuntu-latest
    container: node:18
    steps:
      - run: node --version
        name: Check Node Version 🔦
      - run: npm --version
        name: Check NPM Version 🩺
      - uses: actions/checkout@v3
        name: Checkout Main branch 🧺
      - run: npm install
        name: Install NPM Packages 🔧
      - run: npm run test
        name: Run unit tests 🧪
